server:
  port: ${SERVER_PORT:8088}

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411/}
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/accounts/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: Hystrix
              args:
                name: account-service
                fallbackUri: forward:/fallback/accounts

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: Hystrix
              args:
                name: order-service
                fallbackUri: forward:/fallback/orders

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
    register-with-eureka: false
  instance:
    preferIpAddress: true