version: "3.9"
services:
  cassandra:
    image: cassandra
    ports:
      - "9042:9042"

  mysql:
    image: mysql
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"

  elasticsearch:
    image: elasticsearch:7.16.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"