server:
  port: 8090
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:9000}

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  data:
    cassandra:
      keyspace-name: ${CASSANDRA_SERVER_KEYSPACE:springcloud}
      schema-action: ${CASSANDRA_SCHEMA_ACTION:CREATE_IF_NOT_EXISTS}
      port: ${CASSANDRA_SERVER_PORT:9042}
      username: ${CASSANDRA_SERVER_USERNAME:cassandra}
      password: ${CASSANDRA_SERVER_USERNAME:cassandra}
      local:
        datacenter: ${CASSANDRA_DATACENTER:datacenter1}
      contact:
        point: ${CASSANDRA_SERVER_HOST:localhost}
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411/}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}