server:
  port: 8092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  rabbitmq:
    username: user
    password: password
  cloud:
    stream:
      bindings:
        input: # kuyruğu dinleyen (consume) servis yani notification service - output (produce) diğer servis configlerinde yer alıyor
          destination: notification-queue #kuyruk/topic ismi