server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orderservice?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    username: user
    password: password
  cloud:
    stream:
      bindings:
        output:
          destination: notification-queue #mesajı yazacağımız kuyruk/topic ismi
  zipkin:
    base-url: http://localhost:9411/